
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chrisdaniar
 */
public class Main extends javax.swing.JFrame {
    
    int hanak,hdewasa,harga,beli,total;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tkereta = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbkode = new javax.swing.JComboBox<>();
        blagi = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cmbjurusan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        rdanak = new javax.swing.JRadioButton();
        rddewasa = new javax.swing.JRadioButton();
        tharga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tbeli = new javax.swing.JTextField();
        tbayar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KERETA API");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(160, 30, 180, 40);

        jLabel8.setFont(new java.awt.Font("Trajan Pro 3", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("FORM PENJUALAN TIKET");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 0, 350, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 440, 60);

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nama");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(20, 20, 60, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Kode Kereta");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 60, 110, 15);

        tnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnamaActionPerformed(evt);
            }
        });
        jPanel3.add(tnama);
        tnama.setBounds(120, 10, 190, 30);

        tkereta.setEditable(false);
        jPanel3.add(tkereta);
        tkereta.setBounds(120, 90, 190, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nama Kereta");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 100, 80, 15);

        cmbkode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----- Pilih Kode -----", "KRT111", "KRT222", "KRT333" }));
        cmbkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkodeActionPerformed(evt);
            }
        });
        jPanel3.add(cmbkode);
        cmbkode.setBounds(120, 50, 190, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 80, 320, 130);

        blagi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        blagi.setText("Beli Lagi");
        blagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blagiActionPerformed(evt);
            }
        });
        jPanel1.add(blagi);
        blagi.setBounds(340, 80, 110, 60);

        bkeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(bkeluar);
        bkeluar.setBounds(340, 150, 110, 60);

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setForeground(new java.awt.Color(153, 255, 204));
        jPanel4.setLayout(null);

        cmbjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjurusanActionPerformed(evt);
            }
        });
        jPanel4.add(cmbjurusan);
        cmbjurusan.setBounds(120, 10, 190, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Jurusan");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 20, 80, 20);

        rdanak.setBackground(new java.awt.Color(153, 255, 204));
        buttonGroup1.add(rdanak);
        rdanak.setText("Anak-anak");
        rdanak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdanakActionPerformed(evt);
            }
        });
        jPanel4.add(rdanak);
        rdanak.setBounds(120, 60, 100, 23);

        rddewasa.setBackground(new java.awt.Color(153, 255, 204));
        buttonGroup1.add(rddewasa);
        rddewasa.setText("Dewasa");
        rddewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rddewasaActionPerformed(evt);
            }
        });
        jPanel4.add(rddewasa);
        rddewasa.setBounds(220, 60, 80, 23);

        tharga.setEditable(false);
        jPanel4.add(tharga);
        tharga.setBounds(120, 100, 190, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Jenis Tiket");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(20, 60, 80, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Harga");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(20, 100, 80, 20);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(10, 220, 440, 140);

        jPanel5.setBackground(new java.awt.Color(153, 255, 204));
        jPanel5.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Harga");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(20, 100, 80, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Total Bayar");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(240, 10, 80, 20);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Jumlah Beli");
        jPanel5.add(jLabel11);
        jLabel11.setBounds(20, 10, 80, 20);

        tbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbeliActionPerformed(evt);
            }
        });
        jPanel5.add(tbeli);
        tbeli.setBounds(100, 10, 130, 30);

        tbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbayarActionPerformed(evt);
            }
        });
        jPanel5.add(tbayar);
        tbayar.setBounds(320, 10, 110, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(10, 370, 440, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 430);

        setBounds(0, 0, 479, 466);
    }// </editor-fold>//GEN-END:initComponents

    private void tnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnamaActionPerformed

    private void blagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blagiActionPerformed
    buttonGroup1.clearSelection();
    tharga.setText("");
    tnama.setText("");
    cmbkode.setSelectedItem("----- Pilih Kode -----");
    tkereta.setText("");
    tbeli.setText("");
    tbayar.setText("");
    cmbjurusan.removeAllItems();
        // TODO add your handling code here:
    }//GEN-LAST:event_blagiActionPerformed

    private void cmbkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkodeActionPerformed

    if(cmbkode.getSelectedItem().equals("KRT111")){
    tkereta.setText("MATARMAJA");
    cmbjurusan.removeAllItems();
    cmbjurusan.addItem("---- JURUSAN ----");
    cmbjurusan.addItem("PASAR SENEN - TEGAL");
    cmbjurusan.addItem("PASAR SENEN - MADIUN");
    }
    else if(cmbkode.getSelectedItem().equals("KRT222")){
    tkereta.setText("BRANTAS");
    cmbjurusan.removeAllItems();
    cmbjurusan.addItem("---- JURUSAN ----");
    cmbjurusan.addItem("TANAH ABANG - TEGAL");
    cmbjurusan.addItem("TANAH ABANG - MADIUN");
    }
    else if(cmbkode.getSelectedItem().equals("KRT333")){
    tkereta.setText("BENGAWAN");
    cmbjurusan.removeAllItems();
    cmbjurusan.addItem("---- JURUSAN ----");
    cmbjurusan.addItem("GAMBIR KUTOARJO");
    cmbjurusan.addItem("GAMBIR LEMPUYANGAN");
    }
    else if(cmbkode.getSelectedItem().equals("----- Pilih Kode -----")){
    tkereta.setText("");
    cmbjurusan.removeAllItems();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbkodeActionPerformed

    private void cmbjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjurusanActionPerformed
    if(cmbjurusan.getSelectedItem().equals("---- JURUSAN ----")){
    buttonGroup1.clearSelection();
    tharga.setText("");
}else if(cmbjurusan.getSelectedItem().equals("PASAR SENEN - TEGAL")){
    hanak=30000;
    hdewasa=60000;
}else if(cmbjurusan.getSelectedItem().equals("PASAR SENEN - MADIUN")){
    hanak=35000;
    hdewasa=65000;
}
else if(cmbjurusan.getSelectedItem().equals("TANAH ABANG - TEGAL")){
    hanak=40000;
    hdewasa=70000;
}
else if(cmbjurusan.getSelectedItem().equals("TANAH ABANG - TEGAL")){
    hanak=45000;
    hdewasa=75000;
}
else if(cmbjurusan.getSelectedItem().equals("GAMBIR KUTOARJO")){
    hanak=50000;
    hdewasa=80000;
}
else if(cmbjurusan.getSelectedItem().equals("GAMBIR LEMPUYANGAN")){
    hanak=55000;
    hdewasa=850000;
}
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbjurusanActionPerformed

    private void rdanakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdanakActionPerformed
         if(rdanak.isSelected()){
        tharga.setText(String.valueOf(hanak));
    }
    }//GEN-LAST:event_rdanakActionPerformed

    private void rddewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rddewasaActionPerformed
        if(rddewasa.isSelected()){
        tharga.setText(String.valueOf(hdewasa));
    }
    }//GEN-LAST:event_rddewasaActionPerformed

    private void tbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbeliActionPerformed
        beli=Integer.parseInt(tbeli.getText());
    harga=Integer.parseInt(tharga.getText());
    total=beli*harga;
    tbayar.setText(String.valueOf(total));
        // TODO add your handling code here:
    }//GEN-LAST:event_tbeliActionPerformed

    private void tbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbayarActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        int answer = JOptionPane.showConfirmDialog(null, "Thanks", "Selesai", JOptionPane.OK_OPTION);
        if (answer == JOptionPane.OK_OPTION){
        dispose();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_bkeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton blagi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbjurusan;
    private javax.swing.JComboBox<String> cmbkode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton rdanak;
    private javax.swing.JRadioButton rddewasa;
    private javax.swing.JTextField tbayar;
    private javax.swing.JTextField tbeli;
    private javax.swing.JTextField tharga;
    private javax.swing.JTextField tkereta;
    private javax.swing.JTextField tnama;
    // End of variables declaration//GEN-END:variables
}
